// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_deteccion_y_Registro_de_Alarma.DataAccess.Contexts;

#nullable disable

namespace Sistema_de_deteccion_y_Registro_de_Alarma.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241229154430_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Sistema_de_deteccion_y_Registro_de_Alarma.Domain.Entities.Alert.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Sistema_de_deteccion_y_Registro_de_Alarma.Domain.Entities.Audit.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("Sistema_de_deteccion_y_Registro_de_Alarma.Domain.ValueObjets.Field_operatpor.FieldOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Telephone")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FieldOperators");
                });
#pragma warning restore 612, 618
        }
    }
}
